env:
    browser: true

parserOptions:
    ecmaVersion: 6

extends:
    "eslint:all"

rules:
     one-var: "off"
     padded-blocks: ["error", "never"]
     space-before-function-paren: ["error", "never"]
     no-underscore-dangle: "off"
     vars-on-top: "off"
     newline-after-var: "off"
     camelcase: "off"
     require-jsdoc: "off"
     func-style: ["error", "declaration"]
     newline-before-return: "off"
     init-declarations: "off"
     no-plusplus: "off"
     no-extra-parens: off
     id-length: ["error", {"exceptions": ["i", "k", "x", "y"]}]
     object-shorthand: "off"
     max-statements: ["error", {"max": 30}]
     quotes: ["error", "double", {"avoidEscape": true}]
     object-property-newline: ["error", {"allowMultiplePropertiesPerLine": true}]
     comma-dangle: ["error", "always-multiline"]
     no-magic-numbers: "off"
     no-undefined: "off"
     wrap-iife: ["error", "inside"]
     func-names: "off"
     sort-keys: "off"
     no-warning-comments: "off"
     max-len: ["error", {"ignoreUrls": true}]
     capitalized-comments: "off"
     prefer-destructuring: "off"
     line-comment-position: "off"
     no-inline-comments: "off"
     array-bracket-newline: "off"
     array-element-newline: "off"
     no-multi-spaces: ["error", {"ignoreEOLComments": true}]
     function-paren-newline: "off"
     multiline-comment-style: "off"

     no-unused-vars: "off"
     no-implicit-globals: "off"
     no-bitwise: "off"
     strict: "off"
     no-undef: "off"
     no-param-reassign: "off"
     no-eq-null: "off"
     no-ternary: "off"
     curly: "off"
     eqeqeq: "off"
     max-statements: "off"
