qutebrowser help
================

Documentation
-------------

The following documentation is currently available:

`qutebrowser/`:

* link:../../CHANGELOG.html[Change Log]
* link:../../CONTRIBUTING.html[How to contribute]
* link:../../FAQ.html[Frequently asked questions]
* link:../../INSTALL.html[Installing qutebrowser]
* link:../../README.html[General overview on qutebrowser]

`qutebrowser/doc/`:

* link:../backers.html[People who helped crowdfund qutebrowser]
* link:../quickstart.html[Quick start guide]
* link:../qutebrowser.1.html[qutebrowser manpage]
* link:../stacktrace.html[How to get a stacktrace if qutebrowser crashes]
* link:../stacktrace.html[How to write userscripts]

`qutebrowser/doc/help`:

* link:commands.html[Documentation of available commands]
* link:settings.html[Documentation of available settings]
* link:index.html[The page you're currently on]

If you want to rebuild the website, run `./scripts/asciidoc2html.py --website <outputdir>`.

Getting help
------------

You can get help in the IRC channel
irc://irc.freenode.org/#qutebrowser[`#qutebrowser`] on
http://freenode.net/[Freenode]
(https://webchat.freenode.net/?channels=#qutebrowser[webchat]), or by writing a
message to the
https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser[mailinglist] at
mailto:qutebrowser@lists.qutebrowser.org[].

Bugs
----

If you found a bug or have a feature request, you can report it in several
ways:

* Use the built-in `:report` command or the automatic crash dialog.
* Open an issue in the Github issue tracker.
* Write a mail to the
https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser[mailinglist] at
mailto:qutebrowser@lists.qutebrowser.org[].

License
-------

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
