Flatpak
=======

The flatpak is based on the org.kde.Platform version 5.9 and ships all
additional dependecies of qutebrowser. The platform includes Qt 5.9.

To install the SDK system wide run:

 sudo flatpak install flathub org.kde.Platform//5.9
 sudo flatpak install flathub org.kde.Sdk//5.9

To actually build the flatpak run the following command:

 flatpak-builder --force-clean app-dir org.qutebrowser.qutebrowser.json

To run the flatpak from current build:

 flatpak-builder --run app-dir org.qutebrowser.qutebrowser.json qutebrowser

Installing from a local repository
----------------------------------

You need at least version 0.9.1 of flatpak to build the system, e.g. from
Debian backports.

Export the flatpak application to a local repository:

 flatpak build-export repo app-dir

Add the local repository to your flatpak system (only required once):

 flatpak --user remote-add --no-gpg-verify --if-not-exists qutebrowser-repo repo

Install the flatpak from your local repository:

 flatpak --user install qutebrowser-repo org.qutebrowser.qutebrowser

Run the installed flatpak:

 flatpak run org.qutebrowser.qutebrowser

To update the flatpak from your repository run the build-export command after
building once again. Finally execute the following command to perform the
update from your local repo:

 flatpak update org.qutebrowser.qutebrowser

Or

 flatpak update

to update all installed flatpaks.

Sandbox
-------

Your configuration gets read from 
$HOME/.var/app/org.qutebrowser.qutebrowser/config/qutebrowser/

The sandboxed qutebrowser can read all files from your system, but only write
to your XDG downloads folder.

Direct rendering and sound using pulseaudio are allowed.

Known Limitations
-----------------
