#!/usr/bin/env python3
import os
import sys
import bs4
import re


class StaticGetAttrType(type):
    """Metaclass which simply allows class to define
    a __getstaticattr__ method.
    __getstaticattr__ is the static equivalent of __getattr__.
    """
    def __getattr__(cls, name):
        return cls.__getstaticattr__(name)


class Env(metaclass=StaticGetAttrType):
    """Helper class which allows to access environment variables"""
    def __getstaticattr__(name):
        return os.environ[name]


def read(path):
    """Reads every line of a file

    Return:
        content or None
    """
    with open(path) as f:
        return '\n'.join(f.readlines())


def qexec(*cmds):
    """Executes qutebrowser commands"""
    with open(Env.QUTE_FIFO, 'w') as f:
        for c in cmds:
            f.write("{}\n".format(c))


if __name__ == '__main__':
    soup = bs4.BeautifulSoup(read(Env.QUTE_HTML))
    elems = soup.find_all(["iframe"], src=re.compile(r"(?!javascript).+"))

    qexec(":set-cmd-text :suggest :open 1 ; :: '{}' '".format(
        ";".join(re.sub('^//', 'https://', e.attrs['src'])
                 for e in elems)))
