#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright 2018-2020 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of qutebrowser.
#
# qutebrowser is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# qutebrowser is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with qutebrowser.  If not, see <http://www.gnu.org/licenses/>.

# Change your tor identity.
#
# Set a hotkey to launch this script, then:
#   :bind ti spawn --userscript tor_identity PASSWORD
#
# Use the hotkey to change your tor identity, press 'ti' to change it.
# https://stem.torproject.org/faq.html#how-do-i-request-a-new-identity-from-tor
#

import os
import sys

from argparse import ArgumentParser

try:
    from stem import Signal
    from stem.control import Controller
except ImportError:
    if os.getenv('QUTE_FIFO'):
        with open(os.environ['QUTE_FIFO'], 'w') as f:
            f.write('message-error "Failed to import stem."')
    else:
        print('Failed to import stem.')


if __name__ == '__main__':
    parser = ArgumentParser(prog='tor_identity')
    parser.add_argument('-c', '--control-port', default=9051,
                        help='Tor control port (default 9051).')
    parser.add_argument('-p', '--password', type=str, default=None,
                        help='Tor control port password.')
    args = parser.parse_args()

    with Controller.from_port(port=args.control_port) as controller:
        controller.authenticate(args.password)
        controller.signal(Signal.NEWNYM)
        if os.getenv('QUTE_FIFO'):
            with open(os.environ['QUTE_FIFO'], 'w') as f:
                f.write('message-info "Tor identity changed."')
        else:
            print('Tor identity changed.')
