#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# SPDX-FileCopyrightText: J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Change your tor identity.
#
# Set a hotkey to launch this script, then:
#   :bind ti spawn --userscript tor_identity -p PASSWORD
#
# Use the hotkey to change your tor identity, press 'ti' to change it.
# https://stem.torproject.org/faq.html#how-do-i-request-a-new-identity-from-tor
#

import os
import sys

from argparse import ArgumentParser

try:
    from stem import Signal
    from stem.control import Controller
except ImportError:
    if os.getenv('QUTE_FIFO'):
        with open(os.environ['QUTE_FIFO'], 'w') as f:
            f.write('message-error "Failed to import stem."')
    else:
        print('Failed to import stem.')


if __name__ == '__main__':
    parser = ArgumentParser(prog='tor_identity')
    parser.add_argument('-c', '--control-port', type=int, default=9051,
                        help='Tor control port (default 9051).')
    parser.add_argument('-p', '--password', type=str, default=None,
                        help='Tor control port password.')
    args = parser.parse_args()

    with Controller.from_port(port=args.control_port) as controller:
        controller.authenticate(args.password)
        controller.signal(Signal.NEWNYM)
        if os.getenv('QUTE_FIFO'):
            with open(os.environ['QUTE_FIFO'], 'w') as f:
                f.write('message-info "Tor identity changed."')
        else:
            print('Tor identity changed.')
